homepage:
  path: /
  defaults: { _controller: AppBundle:Default:index }

login:
  path: /login
  defaults: { _controller: AppBundle:Security:login }

logout:
  path: /logout
  defaults: { _controller: AppBundle:Security:logout }

register:
  path: /register
  methods: 'post'
  defaults: { _controller: AppBundle:Security:register }

create_post:
  path: /create-post
  methods: 'post'
  defaults: { _controller: AppBundle:Default:createPost }

remove_post:
  path: /remove
  methods: 'post'
  defaults: { _controller: AppBundle:Default:deletePost }

detail:
  path: /user/{username}
  defaults: { _controller: AppBundle:User:detail }