parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']


    #REPOSITORIES
    user.repository:
        class: AppBundle\Repository\UserRepository
        public: false
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - 'AppBundle\Entity\User'

    post.repository:
        class: AppBundle\Repository\PostRepository
        public: false
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - 'AppBundle\Entity\Post'

    #MANAGERS
    user.manager:
        class: AppBundle\Model\UserManager
        public: true
        arguments:
          - '@user.repository'
          - '@security.password_encoder'

    post.manager:
        class: AppBundle\Model\PostManager
        public: true
        arguments:
          - '@post.repository'